af_api_token: '9483d0aA-...'
app_ids: # app ids
  - 'com.game.me'
  - 'id1234456789'
params:
  lookback: 30 # mintues
  repeat: 30 # minutes
  email_alert: 1000 # first_opens in lookback
  pause_campaigns: 5000 # first_opens in lookback
  timezone: 'Asia/Jerusalem'
  from: 22 #hour
  to: 8 #hour
email: #gmail creds.
  email: <user>
  password: <pass>
  to: 
    - 'user@gmail.com'
    - 'user@company.com'
  messages:
    alert:
      title: "[Pausee Alert] High install rate from Google Ads campaigns"
      body: "The number of installs from Google Ads was {} in the last {} minutes."
    mutate:  
      title: "[Pausee Alert] Campaigns status changed"
      body: "Campaigns status was change to {} for campaigns {}.\n\nFailed to change status to {} for campaigns: {}."

