af_api_token: <8483w03a-...>
app_ids:
  - <com.my.app> # Android app id
  - <id123456789> # iOS app id
params: 
  lookback: 30 #min
  repeat: 30 #min
  email_alert: 1000 
  pause_camapaigns: 5000
  timezone: 'Asia/Jerusalem'
  from: 22 # hour
  to: 8 #hour. Can also be at the day later
email:
  email: <gmail user>
  password: <gmail password>
  to: 
    - <'mymemail@gmail.com'>
    - <'corpemail@google.com'>
  messages:
    alert:
      title: "[Pausee Alert] High install rate alert from Google Ads campaigns"
      body: "The number of installs from Google Ads was {} in the last {} minutes."
    mutate:  
      title: "[Pausee Alert] Campaign mutated"
      body: "Campaigns ids: {} status was change to {}.\n\nFailed to change Campaigns ids: {} status was change to {}."

